# site settings
title: EWEB CDC
subtitle: 
email: info@ewebcdc.com
description: Branching out, Putting down roots, Growing together
url: "" # the base hostname & protocol for your site
author:
street_address: 888 Goodpasture Island Rd
city: Eugene
state: OR
zip_code: 97401
country: United States of America
phone: (541) 345-8887

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"

# social settings
500px_url:
facebook_url: https://www.facebook.com/EWEB-Child-Development-Center-107506842630843
github_url:
gitlab_url:
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed

host: 0.0.0.0

tile-pages:
  - employment.md
  - enrollment.md
  - mission.md
  - team.md
  - parents.md
  - benefits.md

## running the site on gitlab requires the following setting, comment out when running in vagrant
#baseurl: "cdc" # the subpath of your site, e.g. /blog